language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

after_success:
  - gradle/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle